add_newline = false
format = """
$shell $directory $character
"""

[directory]
truncate_to_repo = false
format = "[$path]($style)"
style = "bold yellow"

[git_branch]
always_show_remote = true
format = "[$symbol$remote_name/$branch]($style)"

[git_status]
format = "[$all_status$ahead_behind]($style)"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "bold dimmed blue"
disabled = false

[shell]
fish_indicator = "⋊>"
format = '[\[$indicator\]]($style)'
style = "bold blue"
disabled = false

[username]
format = "[$user]($style)"
show_always = true
